### ISSUE TITLE
Reports of 'image' showing up as text instead

### ISSUE THREAD

**Issue by trnscndnt** [whatagoodbot/miss-groupie#11]
![Screenshot 2022-11-04 at 09-53-52 RVRB](https://user-images.githubusercontent.com/38389681/200032292-a934d33f-1592-4ea8-b819-01f29d142d0a.png)

**Comment by trnscndnt** [comment]
This is regarding about the !addroomgreetings !alias

**Comment by notABluesSinger** [comment]
As this works differently to previous clients, I'm going to need to change the structure of the alias and greeting commands. Leaving this task open as I will address this issue shortly
