### ISSUE TITLE
Room Greeting reverting to previous

### ISSUE THREAD

**Issue by CGives** [whatagoodbot/miss-groupie#12]
The Room Greeting is often reverting to a previous greeting despite being set with the new one multiple times. It did appear as the new version for awhile but then reverted to one that was set days prior.

**Comment by notABluesSinger** [comment]
Any aliases or greetings are picked randomly from an array of greetings that have been entered - there isn't currently a way to remove old greetings.

For the moment, please let me know if you'd like me to clear any greetings down and I'll leave this issue open to track a new command to give the ability to remove greetings
