### ISSUE TITLE
Whisper command not working

### ISSUE THREAD

**Issue by SoundSherpa** [whatagoodbot/miss-groupie#31]
Seems that whispers arent working to users with a space in their name. Found another user without a space this was happening to as well but consistently every time we tested with a user with a space, they wouldnt see it. It may also have something to do with the autocomplete?
When you whisper someone it usually gives a message saying you sent a whisper to that user. In the cases it doest work, it instead says in the message that you are whispering Miss Groupie.

**Comment by SoundSherpa** [comment]
![Screenshot 2022-12-02 142236](https://user-images.githubusercontent.com/72993376/205379353-b65163b3-39eb-4ddf-9fde-2ca5bd4bd18f.png)

Working vs non working whisper attached.

**Comment by notABluesSinger** [comment]
There's an open issue within RVRB that I beleive has been resolved. I'll close this for now, but please let me know if that's not the case
